name: real_estate_1a
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.2
  cupertino_icons: ^1.0.8
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.2
  flutter_bloc: ^9.1.1
  internet_connection_checker: ^3.0.1
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1
  conditional_builder_null_safety: ^0.0.6
  flutter_svg: ^2.2.4
  fluttertoast: ^9.0.0
  flutter_icon_snackbar: ^1.2.1
  flutter_styled_toast: ^2.3.0
  page_transition: ^2.2.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.1
  intl: ^0.20.2
  animate_do: ^5.1.0
  dartz: ^0.10.1
  pin_code_fields: ^9.3.0
  flutter_animate: ^4.5.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.2.0
  firebase_auth: ^6.4.0
  flutter_local_notifications: ^17.2.3
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  drop_down_list: ^2.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  injectable: ^2.7.1+4
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.14.1
  injectable_generator: ^2.12.1
  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/icon/
    - assets/images/

  fonts:
    - family: poppins
      fonts:
        - asset: fonts/poppins/poppins-regular.ttf
          weight: 400
        - asset: fonts/poppins/poppins-semibold.ttf
          weight: 600
        - asset: fonts/poppins/poppins-medium.ttf
          weight: 500
