// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_MkYGIK1BIzT3Ftk1UmAw3IQPl7x-SY',
    appId: '1:116864924427:web:f8eb68584aa1bffe4cc00e',
    messagingSenderId: '116864924427',
    projectId: 'real-estate-9b30e',
    authDomain: 'real-estate-9b30e.firebaseapp.com',
    storageBucket: 'real-estate-9b30e.firebasestorage.app',
    measurementId: 'G-VZXR9QXF7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl20mkdsxzHz3FU8Dao3RfU_ZD86lOuUU',
    appId: '1:116864924427:android:2e0999a40664378c4cc00e',
    messagingSenderId: '116864924427',
    projectId: 'real-estate-9b30e',
    storageBucket: 'real-estate-9b30e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwX46Dm7XfCXjC8Fq54dvB7GFq4o__RYo',
    appId: '1:116864924427:ios:250363f441fa56fb4cc00e',
    messagingSenderId: '116864924427',
    projectId: 'real-estate-9b30e',
    storageBucket: 'real-estate-9b30e.firebasestorage.app',
    iosClientId: '116864924427-hfil8o4unpf6va8s48c13lio1amt0h8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate1a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwX46Dm7XfCXjC8Fq54dvB7GFq4o__RYo',
    appId: '1:116864924427:ios:250363f441fa56fb4cc00e',
    messagingSenderId: '116864924427',
    projectId: 'real-estate-9b30e',
    storageBucket: 'real-estate-9b30e.firebasestorage.app',
    iosClientId: '116864924427-hfil8o4unpf6va8s48c13lio1amt0h8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate1a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8_MkYGIK1BIzT3Ftk1UmAw3IQPl7x-SY',
    appId: '1:116864924427:web:af05cb893924cfcc4cc00e',
    messagingSenderId: '116864924427',
    projectId: 'real-estate-9b30e',
    authDomain: 'real-estate-9b30e.firebaseapp.com',
    storageBucket: 'real-estate-9b30e.firebasestorage.app',
    measurementId: 'G-4H22DSVRQN',
  );

}